local builtin = require('telescope.builtin')
vim.keymap.set('n', '<C-p>', builtin.find_files, {})
vim.keymap.set('n', '<leader>fg', builtin.git_files, {})
vim.keymap.set('n', '<leader>a', function ()
  builtin.grep_string({ search = vim.fn.input("Grep For > ")})
end)
vim.keymap.set('v', '<leader>a', builtin.grep_string)
vim.keymap.set('n', '<C-b>', builtin.buffers, {})
vim.keymap.set('n', '<C-c>', builtin.commands, {})
