#!/usr/bin/env bash
#
# bootstrap installs things.

cd "$(dirname "$0")/.."
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

link_file () {
  local src=$1 dst=$2

  # Always overwrite_all
  rm -rf "$dst"
  success "removed $dst"

  ln -s "$1" "$2" && ls -l "$2"
  success "linked $1 to $2"
}

install_dotfiles () {
  info 'installing dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    info "working on: $src"
    dst="$HOME/.$(basename "${src%.*}")"
    link_file "$src" "$dst"
  done
}

install_neovim_config () {
  info 'installing neovim files'

  src="$DOTFILES_ROOT/neovim/*"
  dst="$HOME/.config/nvim/"

  # Clean up and then make sure neovim folder exists
  rm -rf $dst
  mkdir -p $dst

  ln -s $src $dst
  success "linked $src to $dst"
}

install_ghostty_config () {
  info 'installing ghostty files'

  src="$DOTFILES_ROOT/ghostty/*"
  dst="$HOME/.config/ghostty/"

  # Clean up and then make sure folder exists
  rm -rf $dst
  mkdir -p $dst

  ln -s $src $dst
  success "linked $src to $dst"
}

install_dotfiles
install_neovim_config
install_ghostty_config

echo ''
echo '  All installed!'
